### ISSUE TITLE
Redirect link issue

### ISSUE THREAD

**Issue by sumit-subedi** [zougari47/portfolio#1]
Hey just visited your website through developer portfolios and your link to GitHub page is not working. Thought you would appreciate it. Cheers!

PS: Liked your projects showcase card, might steal it.

**Comment by zougari47** [comment]
Please can specify a link, I checked and all things seem working. please provide a link.

I'm glad you like it. you can use the whole website as you like. That's why I make it open source to give back to the community. I'm currently working on guide documentation. If you like the repository you can give a ⭐. 

Thank you.

**Comment by sumit-subedi** [comment]
Github link on your footer it redirects to githubcom, "." is missing.

**Comment by zougari47** [comment]
I fixed it ✅ thank you 🙌
